# लाइव डेटाबेस का URL (हमने होस्ट और पोर्ट को वेरिएबल बना दिया)
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/defaultdb?sslmode=require&allowPublicKeyRetrieval=true&useSSL=true

# लाइव डेटाबेस का यूजरनेम
spring.datasource.username=${DB_USER}

# लाइव डेटाबेस का पासवर्ड (यह अब गिटहब पर नहीं दिखेगा)
spring.datasource.password=${DB_PASSWORD}

# बाकी सेटिंग्स वैसी ही रहेंगी
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true